import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import AuthContainer from "@/components/authContainer";
import PushContainer from "@/components/pushContainer";
import QueryContainer from "@/components/queryContainer";
import Header from "@/components/layout/header";
import Aside from "@/components/layout/aside";
import Footer from "@/components/layout/footer";
import Main from "@/components/layout/main";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
      >
        <QueryContainer>
          <AuthContainer>
            <PushContainer>
              <div className="flex flex-col min-h-screen">
                <Header />
                <div className="flex flex-1">
                  <Aside />
                  <Main>{children}</Main>
                </div>
                <Footer />
              </div>
            </PushContainer>
          </AuthContainer>
        </QueryContainer>
      </body>
    </html>
  );
}
